### ISSUE TITLE
Release checklist doesn't have links in it.

### ISSUE THREAD

**Issue by nebril** [cilium/release#261]
This issue https://github.com/cilium/release/issues/258 was created using new `checklist` utility, links in the template are not clickable in the checklist and you need to refer to the remplate file to find out what the link is.

Attached screenshot with issue visible: 
![image](https://github.com/user-attachments/assets/8f4cdaa5-f91e-445d-93a3-52e863c7021c)

**Comment by aanm** [comment]
I think it's related with this one as well? https://github.com/cilium/release/issues/256 cc @joestringer :pleading_face:
